version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    volumes:
      - .:/app
    env_file: .env.test
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
