version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    env_file: .env.prod
    command: ["bash", "-c", "bundle exec rails s -b 0.0.0.0"]
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: